    name: lab_rat_storage
    version: 1.0.8
    description: Simple package for work with session storage and local storage. Allow to JSON.encode / JSON.decode
    author: Laboratory Rat <Oleg.Timofeev20@gmail.com>
    homepage: https://github.com/laboratory-rat/dart.storage
    enviroent: 
        sdk: ">=1.24.0 < 2.0.0"


